env:
  global:
  - GH_REF: github.com/FTSRG/thesis-works.git
  - secure: "cuJGF4548aUGpL48Ev0jn5raPyXohcZ/BHcJza1mxpAn3aC31CK7piavs/t7TagM9yAjuo1T9z5ALulA6QRb+j1XxsMhoC+ID3g6LDLb63byfDvcTZxTt8McLX1BuaadYRSZ70lAKzDaCXaOR8Hr34PRMfqYXY/q/7EPZxDs6KyF8VmxVGIqfwkA1nIimBJD4nTLqUiuyoBoJTKqloq63YJe7G51rlHI4Sn0UEwq3i52rOff0rbrPJwXOPH01LHwqMcqvviRA7DSVjsXFQL8jyy2QFhHcSjsvT0X9MUnZ0/tDYwlfzuBUwuoC6sExpF4ac2z6p6QxYa2TgvKmSZFAke2gZK/Nka70NeIimdwZ4xV6tGVTmyXi8UGEX810evmeZJl3IxyDUtCnfUkv4FokV7UYyOMUnqdCJTDFroSwVdgWFIWacnr3lhEKLmS485XBEaMvv2WZg40tGqQnpz24wiN5Ba12Q7QG9KV1gcL+JF46uG3Z0YGW4Eih4Xvp5JRZqGizYxpRcFKwdurl9ZSKDLRCiWoX6TJgLofBhAKo4oZmRUyFZqgHGf6kIFbO6DX/75XWalNuAmHDAu2tWsAAZYwp4up/HjJEa/RYMY1nERcQkvsnj9jtJGdbF+ttRknMLgy/TYcWvpBYni9ihll4VaVQRHsgmvIHT+xIOsYofg="
branches:
  only:
    - source
language: ruby
rvm:
  - 2.3.1
script:
- bundle exec jekyll build
- ./deploy.sh
