# Site settings
title: Thesis works
#email: your-email@domain.com
#description: >
#    Thesis works.
baseurl: "/thesis-works" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  FTSRG

# Build settings
markdown: kramdown

gems: ['jekyll/scholar']

scholar:
    repository: pdfs
    style: chicago-fullnote-bibliography
    bibliography_template: bib
    sort_by: author
