name: Build Jekyll site and deploy
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Install and Build 🔧
        run: |
          sudo apt update && sudo apt install -y ruby
          sudo gem install bundler:1.16.1
          bundle install
          bundle exec jekyll build
          mkdir build
          cp -r _site/* build/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92  # 4.1.4
        with:
          branch: gh-pages
          folder: build
        if: github.event_name == 'push' && github.ref == 'refs/heads/source'
